version: 2.1
jobs:
  build-job:
    docker:
      # specify the version you desire here
      - image: circleci/android:api-26-alpha

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/firstapps/
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}

      - restore_cache:
          keys: 
            - v1-dependencies-{{ checksum "package.json" }}
            - V1-dependencies-   

      #- run: npm install
      
      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules
      - run:
          name: Setup emulator
          command: sdkmanager "system-images;android-22;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-22;default;armeabi-v7a"
      - run:
          name: Launch emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel on
          background: true
      - run:
          name: Run Tests
          command: ./gradlew :demo:connectedAndroidTest
 
      - run: npm run test 
      # for react native start
      #- run: yarn react-native start
      # for android build apk
      - run: npm android
      


  deploy-job:
       docker:
         - image: circleci/node:10.14.2
       #working_directory: ~/firstapps
       steps:
         - restore_cache:
             keys:
              - v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
         #- save_cache:
            # key: 
             # - v1-storybook-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }} 
         

         - run:
             name: deply apk to firebase 
             command:  firebase appdistribution:distribute C:\Users\hp\Documents\firstapps\firstapps\android\app\build\outputs\apk\debug\app-debug.apk --app 1:139719722795:android:30a6217b4724daec04676e --release-notes "Bug fixes1 and improvements"

workflows:
  version: 2.1

  -deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: main

