version: 2.1
jobs:
  build-job:
    docker:
      # specify the version you desire here
      - image: cimg/node:12.16

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/firstapps
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}  

      - run: yarn  install
      
      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      #- run: yarn run test
      - run:
          name: jest tests
          command: |
            mkdir -p test-results/jest
            yarn run test
          environment:
            JEST_JUNIT_OUTPUT: test-results/jest/junit.xml
      - persist_to_workspace:
          root: ~/firstapps
          paths:
            - node_modules

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results

      


  deploy-job:
    working_directory: ~/firstapps/firstapps/
    docker:
      - image: circleci/android:api-26-node
       
    steps:
      - checkout:
          path: ~/firstapps/

      - attach_workspace:
          at: ~/firstapps

      - restore_cache:
          keys:
            - v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
         #- save_cache:
            # key: 
             # - v1-storybook-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }} 
      - run:
          name: show directory 
          command: pwd
          
      - run:
          name: Install Firebase
          command: curl -sL firebase.tools | bash

      - run:
          name: firebase login
          command: firebase deploy --token=$FIREBASE_DEPLOY_TOKEN -y

      - run:
          name: deply apk to firebase 
          command:  firebase appdistribution:distribute C:\Users\hp\Documents\firstapps\firstapps\android\app\build\outputs\apk\debug\app-debug.apk --app=$APP_ID --release-notes "Bug fixes1 and improvements"

workflows:
  version: 2.1

  -deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: main

