orbs:
  deploygate: 'jmatsu-sandbox/deploygate-upload-app@dev:first'
version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/android:api-28-alpha'
    steps:
      - checkout
      - run: ./gradlew assembleDebug
      - deploygate/upload-app:
          api_key: $APP_ID
          owner_name: habib@techmatetech.com
          app_path: firstapps/android/app/build/outputs/apk/debug/app-debug.apk
          visibility: public
workflows:
  deployment:
    jobs:
      - build
