version: 2.1
jobs:
  node:
    working_directory: ~/firstapps
    docker:
      - image: cimg/node:12.16

    steps:
      - checkout:
          path: ~/firstapps

      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run:
          name: Yarn Install For React-Native
          command: yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules
      #Test Eslint and flow 
      - run:
          name: Eslint Test
          command: yarn run eslint

      #Jest Test for android 1
      - run:
          name: Jest Tests
          command: |
            mkdir -p test-results/jest
            yarn run test
          #environment:
            #JEST_JUNIT_OUTPUT: test-results/jest/junit.xml

      - persist_to_workspace:
          root: ~/firstapps
          paths:
            - node_modules

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results

 # macos-build-and-test:
  #  working_directory: ~/firstapps
   # macos:
    #  xcode: 11.3.0
    #environment:
     # FL_OUTPUT_DIR: output
      #FASTLANE_LANE: test
      #FIREBASE_TOKEN: 1//037Oa2-I9YUHBCgYIARAAGAMSNwF-L9IrH0fad9cGaaTCeCtuGq2aoxzaJkirk8wQ4-_WUVGSlsc7bSldRkMI9oCcE0Qa2v-i2uw

    #steps:
     # - checkout
      #- restore_cache:
       #   key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      #- restore_cache:
       #   key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      #- run: yarn install

      #- save_cache:
       #   key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
        #  paths:
         #   - ~/.cache/yarn

      #- save_cache:
       #   key: node-v1-{{ checksum "package.json" }}-{{ arch }}
        #  paths:
         #   - node_modules

      #- restore_cache:
       #   key: bundle-v1-{{ checksum "ios/Gemfile.lock" }}-{{ arch }}

      #Pods directory is ignored to match default RN setup, but can also check them into source control
      #https://guides.cocoapods.org/using/using-cocoapods.html#should-i-check-the-pods-directory-into-source-control
      #- restore_cache:
       #   key: pods-v1-{{ checksum "ios/Podfile.lock" }}-{{ arch }}

      #- run: 
       #   command: pod install
        #  working_directory: ios

      #- run: 
       #   command: bundle install
        #  working_directory: ios

      #- save_cache:
       #   key: bundle-v1-{{ checksum "ios/Gemfile.lock" }}-{{ arch }}
        #  paths:
         #   - vendor/bundle

      #- save_cache:
       #   key: pods-v1-{{ checksum "ios/Podfile.lock" }}-{{ arch }}
        #  paths:
          #  - ios/Pods

      #- run:
       #   name: Fastlane
        #  command: bundle exec fastlane $FASTLANE_LANE
         # working_directory: ios

      #- store_artifacts:
       #   path: output
          
      #- store_test_results:
       #   path: output/scan
            
  android-build-and-test:
    working_directory: ~/firstapps/android
    docker:
      - image: circleci/android:api-29-node
    environment:
      FL_OUTPUT_DIR: output
      FAST_PARAMETER: android
      FASTLANE_LANE: test
      FIREBASE_TOKEN: 1//03hdclu-WsZuICgYIARAAGAMSNwF-L9IrYcSVLfiWmaDRb0kBtW5nTbFjkLUW48PzNFvcK6190apIn8frcrVuYoveVJ3cK1w3xwY
      #JVM_OPTS: -Xmx3200m 
    steps:
      - checkout:
          path: ~/firstapps

      - attach_workspace:
          at: ~/firstapps

      - restore_cache:
          key: bundle-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}

      - restore_cache:
          key: android-jars-v1-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Gradle Execute Permission
          command: chmod +x ./gradlew
      
      - run:
          name: Bundle Install For React-Native
          command: bundle install
          
      - run: bundle update fastlane
      
      - run:
          name: Download Gradle Dependencies
          command: ./gradlew androidDependencies
      

      - save_cache:
          key: bundle-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}
          paths:
            - vendor/bundle
      - save_cache:
          key: android-jars-v1-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
          paths:
            - ~/.gradle
      

      #- run: fastlane action gradleqaq
       #- run: yarn android
      
      #- run:
       #   name: Run Gradle Tests For Android
        #  command: ./gradlew lint test

      #- store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/ 
       #   path: app/build/reports
        #  destination: reports

      #- store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
       #   path: app/build/reports

     # - run:
      #    name: fastlane tests
       #   command: |
        #    mkdir -p test-results/fastlane
         #   bundle exec fastlane $FASTLANE_LANE
          #  mv fastlane/report.xml test-results/fastlane

      #- store_test_results:
       #   path: test-results 

      #- store_artifacts:
       #   path: test-results

      - run:
          name: Install Firebase Tools
          command: curl -sL firebase.tools | bash

      - run:
          name: Add Fastlane Firebase App Distribution Plug-In
          command: bundle exec fastlane add_plugin firebase_app_distribution

      - run:
          name: Build Debug APK and Release APK To Firebase App Distribution
          command: bundle exec fastlane android $FAST_PARAMETER $FIREBASE_TOKEN
 

      
      

      

workflows:
  node-android:
    jobs:
      - node
      - android-build-and-test:
          requires:
            - node
     # - macos-build-and-test:
      #    requires:
       #     - node