version: 2.1
jobs:
  node:
    working_directory: ~/firstapps
    docker:
      - image: circleci/android:api-26-node8-alpha
    environment:
      _JAVA_OPTIONS: "-Xmx1500m"

    steps:
      - checkout

      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - restore_cache:
          key: bundle-v1-{{ checksum "android/Gemfile.lock" }}-{{ arch }}

      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      
      - run:
          name: Bundle Install 
          command: bundle install --path vendor/bundle
          working_directory: android

      - save_cache:
          key: bundle-v1-{{ checksum "android/Gemfile.lock" }}-{{ arch }}
          paths:
            - android/vendor/bundle

      - run:
          name: jest tests
          command: |
            mkdir -p test-results/jest
            yarn run test
          environment:
            JEST_JUNIT_OUTPUT: test-results/jest/junit.xml

      - persist_to_workspace:
          root: ~/firstapps
          paths:
            - node_modules

      
      - run:
          name: fastlane tests
          command: |
            mkdir -p test-results/fastlane
            bundle exec fastlane test
            mv fastlane/report.xml test-results/fastlane
      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results

      
           
  android-build-and-test:
    working_directory: ~/firstapps/android
    docker:
      - image: circleci/android:api-26-node8-alpha
    environment:
      _JAVA_OPTIONS: "-Xmx1500m"
    steps:
      - checkout:
          path: ~/firstapps
    

      - run: 
          name: Check MD5 on files
          command: |
            md5sum android/build.gradle
            md5sum android/app/build.gradle            
            cat android/app/build.gradle | sed -n -e '/dependencies/,$p' > android.app.build.gradle.deps
      - restore_cache:
          key: android-jars-v1-{{ checksum "android/build.gradle" }}-{{ checksum  "android.app.build.gradle.deps" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
          working_directory: android
      - save_cache:
          key: android-jars-v1-{{ checksum "android/build.gradle" }}-{{ checksum  "android.app.build.gradle.deps" }}
          paths:
            - ~/.gradle

      
      
      
      - run: 
          name: Build android js bundle
          working_directory: android
          command: |
            ./gradlew bundleReleaseJsAndAssests
      - run: 
          name: build Android APK
          working_directory: android
          command: |
            ./gradlew assembleRelease -x bundleReleaseJsAndAssests
  
         # name: Build Debug APK
          #command: |
           #  mkdir -p apk/android
            # bundle exec fastlane test
             #./gradlew bundleRelease
      

workflows:
  node-android:
    jobs:
      - node
      - android-build-and-test:
          requires:
            - node