# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :beta do
  desc "Description of what the lane does"
  lane :beta do
    # ...
    build_app (scheme: "firstapp")
  
    firebase_app_distribution(
      app: "1:912282131729:ios:7e3b3b1ac70de4a50600b0",
      testers: "muhammad@apollo.inc, falak@apollo.inc"
    )
    # ...
  end
end
