# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane


default_platform (:android)

platform :android do
  lane :android do
    gradle(
      task: 'assemble',
      build_type: 'Release'
    )
    firebase_app_distribution(
      app: "1:139719722795:android:30a6217b4724daec04676e",
      testers: "muhammad@apollo.inc, falak@apollo.inc",
      export FIREBASE_TOKEN=1//03hdclu-WsZuICgYIARAAGAMSNwF-L9IrYcSVLfiWmaDRb0kBtW5nTbFjkLUW48PzNFvcK6190apIn8frcrVuYoveVJ3cK1w3xwY

    ) 
  end
  
end
