# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  lane :android do
    gradle(
      task: 'assemble',
      build_type: 'Release'
    )
    firebase_app_distribution(
      app: "1:139719722795:android:30a6217b4724daec04676e",
      testers: "muhammad@apollo.inc, falak@apollo.inc"  
    ) 
  end
  desc "Submitting to alpha"
  lane :alpha do
    gradle(task: "clean assembbleRelease")
    upload_to_play_store(track: 'alpha')
  end
  desc "promote alpha build to beta"
  lane :deploy do
    upload_to_play_store(track: 'alpha', track_promote_to: 'beta')
  end
  
    

  
end
